language: bash

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install guile; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install terminal-notifier; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brightness; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:duggan/bats --yes; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq bats; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq -y guile-2.0-dev; fi
  
script:
  - sudo make install
