#!/usr/bin/env bash

action=$1

if [[ $action == 'yn' ]]; then
  action='yesterday-and-today-eng-notebook'
elif [[ $action == 'week' ]]; then
  action='note week'
fi

$SOJI_DIR/subcommands/$action "${@:2}"
