#!/usr/bin/env bash

if [ -z $SOJI_DIR ]; then
  . ~/.config/soji/sojirc
fi

action=$1

if [[ $action == 'yn' ]]; then
  action='yesterday-and-today-eng-notebook'
elif [[ $action == 'week' ]]; then
  action='note week'
elif [[ $action == '' ]]; then
  action='note log'
fi

$SOJI_DIR/subcommands/$action "${@:2}"
