#!/usr/bin/env bash

soji dim
soji log "break" "break"

os_x=`uname -a | fgrep -i 'Darwin'`
if [ "$os_x" != "" ]; then
    crontab -l | { cat; echo "`date -v +5M +'%M %H %d %m *'` /usr/local/bin/soji bright"; } | crontab -
else
    crontab -l | { cat; echo "`date +'%M %H %d %m *' --date '+5 min'` /usr/local/bin/soji bright"; } | crontab -
fi



