#!/usr/bin/env bash
xrandr --output eDP1 --display ":0" --brightness 1
xrandr --output HDMI1 --display ":0" --brightness 1
xrandr --output eDP-1 --display ":0" --brightness 1
xrandr --output DP-1 --display ":0" --brightness 1
