#!/usr/bin/env bash

#prompt
RED="\[\033[1;31m\]"
YELLOW="\[\033[1;33m\]"
GREEN="\[\033[1;32m\]"
WHITE="\[\033[1;97m\]"
NOCOLOR="\[\033[1;0m\]"

todays_note_file=`soji note-path log`
pom_count=`cat $todays_note_file 2> /dev/null | grep -i "** start" | wc -l`
poms=""
if [ $pom_count -lt 4 ]; then
  poms="$WHITE pomodoros $RED $pom_count"
elif [ $pom_count -lt 8 ]; then
  poms="$WHITE pomodoros $YELLOW $pom_count"
else
  poms="$WHITE pomodoros $GREEN $pom_count"
fi

lunch=""
cat $todays_note_file 2> /dev/null | grep -i "** lunch" &> /dev/null
if [[ $? == 0 ]]; then
  lunch="$WHITE lunch $GREEN[✔]"
else
  lunch="$WHITE lunch $RED[✘]"
fi

meditation=""
cat $todays_note_file 2> /dev/null  | grep -i "** Meditation" &> /dev/null
if [[ $? == 0 ]]; then
  meditation="$WHITE meditation $GREEN[✔]"
else
  meditation="$WHITE meditation $RED[✘]"
fi

journal=""
if [ -e `soji note-path journal` ]; then
  journal="$WHITE journal $GREEN[✔]"
else
  journal="$WHITE journal $RED[✘]"
fi

meeting_count=`cat $todays_note_file 2> /dev/null | grep -i "** meeting" | wc -l`
meetings="$WHITE meetings $GREEN $meeting_count"

echo "$journal $meditation $lunch $poms $meetings"
