#!/usr/bin/env bash

type=${1:-eng}
days_ago=${2:-0}

if [[ $type == 'eng' ]]; then
  echo $SOJI_NOTES_DIR/engineering-notebook-`date +%Y-%m-%d --date "$days_ago days ago"`.md
elif [[ $type == 'regular' ]]; then
  echo $SOJI_NOTES_DIR/note-`date +%Y-%m-%d-at-%H:%M`.md
elif [[ $type == 'week' ]]; then
  day_of_week=`date +%u`
  for i in `seq 0 $(expr $day_of_week - 1)`; do echo $SOJI_NOTES_DIR/engineering-notebook-`date +%Y-%m-%d --date "$i days ago"`.md; done | xargs
fi
