#!/usr/bin/env bash

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

os_x=`uname -a | fgrep -i 'Darwin'`

if [ "$os_x" != "" ]; then
    /usr/local/bin/terminal-notifier -message "$1" -sound "Pop"
else
    echo $1
    notify-send -i $SOJI_DIR/zen.jpeg "$1"
fi