#!/usr/bin/env bash
os_x=`uname -a | fgrep -i 'Darwin'`
if [ "$os_x" != "" ]; then
    crontab -l | { cat; echo "`date -v +25M +'%M %H %d %m *'` /usr/local/bin/soji break"; } | crontab -
else
    crontab -l | { cat; echo "`date -v +25 +'%M %H %d %m *'` /usr/local/bin/soji break"; } | crontab -
fi

