#!/usr/bin/env bash
echo "start,$1,`date +'%s'`" >> $SOJI_EVENTS_DIR/events-`date +%Y-%m-%d`.csv
echo -e "\n### Pom -- $1 -- `date +'%I:%M%p'`" >> `$SOJI_DIR/soji notebook-path`
$SOJI_DIR/soji schedule_break
$SOJI_DIR/soji schedule_notification "20 min left! On the task $1" 5
$SOJI_DIR/soji schedule_notification "15 min left! On the task $1" 10
$SOJI_DIR/soji schedule_notification "10 min left! On the task $1" 15
$SOJI_DIR/soji schedule_notification "ONLY 5 min left! On the task $1" 20
